# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the entire repository into the container
COPY . .

# Upgrade pip and install build tools
RUN pip install --upgrade pip \
    && pip install .

# Expose port if needed (optional, depends on uv configuration)

# Use the entrypoint installed by pyproject.toml for the MCP server
CMD ["explorium-mcp-server"]
