[project]
name = "mcp-explorium"
version = "0.0.1"
description = "MCP server for the Explorium API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.3.0",
    "requests>=2.32.3",
]
